#!/usr/bin/env bash
# this script to use while and if to loop 10 times with special pherases

counter=0

while [ $counter -lt 10 ]
do
	if [ $counter -eq 3 ]
	then
		echo "bad luck"
		(( counter++ ))
	elif [ $counter -eq 7 ]
	then
		echo "good luck"
		(( counter++ ))
	else
		echo "Best School"
		(( counter++))
	fi
done
