#!/usr/bin/env bash
#bash script that configurates an ubuntu server

cp /etc/hosts ~/hosts.new
echo "127.0.02		localhost">~/hosts.new
echo "8.8.8.8		facebook.com">>~/hosts.new
cp -f ~hosts.new /etc/hosts
